### ISSUE TITLE
How can I reproduce the same thing for my portfolio

### ISSUE THREAD

**Issue by Tirth27** [andyruwruw/andyruwruw.com#1]
Hi, 

The Material UI website is awesome, and I like the simplified design and choice of graphic. 

I am interested in customising the existing website for my portfolio. Is there any way to reproduce the things on my end?

Thanks, 💯

**Comment by andyruwruw** [comment]
You're free to take a look through the code and re-use parts that you like!

Keep in mind the graphics are licensed to me, so if you use them there could be issues. [Here's where I purchased them](https://craftwork.design/downloads/category/illustrations/), you can buy the same ones I used or find a pack that best fits your needs.

The site is made using React.js, if you're familiar with the framework then the code should make sense. You can clone the repo and run `npm install` and `npm run start` to get things started.

The biggest things that make the site look nice is the use of [scroll-snap](https://www.npmjs.com/package/scroll-snap) to lock onto different sections, the use of [react-parallax-tilt](https://www.npmjs.com/package/react-parallax-tilt) to make the graphics a little more dynamic, and as you noted `@material-ui`.

If you have any questions about how anything is done feel free to reach out.
